### PR TITLE
[v0.94] mptcp: Fix compilation error when CONFIG_MPTCP is undefined

### PR DESCRIPTION
**Pull request by lenormf**

### CODE REVIEW

**Comment by matttbe** [comment]
Hi Frank,

Thank you for the patch!

I just included in mptcp_trunk + v0.94 and v0.93 with small modifications.
https://github.com/multipath-tcp/mptcp/commit/0bb9c5d61fbe5a1edc68c94d14a6380b69468e29

Maybe next time, please send validated patches only for `mptcp_trunk` (except if it is specific to a previous version of course), add a signoff-by, mention what it fixes to ease the backports and verify it with checkcheck.pl. Ideally it is preferred to send patch to mptcp-dev ML for the visibility but that's another topic. We tried to summarise that on our wiki: http://multipath-tcp.org/pmwiki.php/Developer/SubmitAPatch
But there are more details in the official kernel documentation because the workflow is the same ;-)

**Comment by matttbe** [comment]
Hi @cpaasch ,

I didn't include this patch in `mptcp_v0.95` branch. Because `mptcp_trunk` has not been updated yet, I don't know if you prefer using `git merge` or `git cherry-pick -xs` :)

**Comment by cpaasch** [comment]
@matttbe Let's use cherry-picks from now on.

**Comment by matttbe** [comment]
@cpaasch good idea! Just cherry-picked the fix on mptcp_v0.95 then!

**Pull request closed without merging**
