### PR TITLE
bugfix mptcp_sched.c: select lowpriosk before backupsk if bestsk is not valid

### PR DESCRIPTION
**Pull request by ghost**
Now lowpriosk is only selected if all the subflows are lowprio subflows. This patch ensures that lowpriosk is used if there isn't a valid bestsk subflow. When there aren't valid bestsk and lowpriosk subflows, then backupsk is used.

Apart from that, ensure that sk is set to NULL if bestsk, lowpriosk and backupsk are NULL.

### CODE REVIEW

**Comment by cpaasch** [comment]
Hello,

unfortunately this change would make the scheduler select the lowpriosk even if there is still another subflow available but it's congestion window is full. E.g., if you try it out with an iperf session and limit the bandwidth on the high-priority subflow, you will see packets going over the backup-flow. This should not be the desired behavior.

I would be fine with sending over the backup-sk in case tp->pf is set to 1. That way we handle the case where there is a path-failure on the high-prio subflow.

**Comment by ghost** [comment]
Thanks! the congestion window point is really a key point.
So, I understand that the lowpriosk should only be used if all the subflows are low_prio ones or if all the "high_prio" subflows failed. 
Then, we have the backupsk pointer. This pointer could be a low_prio or high_prio subflow depending on the for loop. However, I understand that this backupsk pointer should always be one "high_prio" subflow. What do you think?

**Comment by cpaasch** [comment]
> On Dec 9, 2014, at 8:07 AM, chrpinedo notifications@github.com wrote:
> 
> Thanks! the congestion window point is really a key point.
> So, I understand that the lowpriosk should only be used if all the subflows are low_prio ones or if all the "high_prio" subflows failed. 

Indeed. At least, lowpriosk should not be used if there is still a high-prio subflow who has connectivity.

> Then, we have the backupsk pointer. This pointer could be a low_prio or high_prio subflow depending on the for loop. However, I understand that this backupsk pointer should always be one "high_prio" subflow. What do you think?

I think the backupsk pointer can be either low- or high-prio. It should be used when a segment has been sent once on all subflows but still has not been acknowledged.
Btw., it looks to me that we might select the backupsk too early:
E.g., two subflows (A and B) and segment "1" has been sent on A while B's congestion window is full (mptcp_is_available returns FALSE). Then, we will set A as backupsk (because mptcp_dont_reinject_subflow returns TRUE). But B will not be chosen as an alternative because the congestion window is full. This seems a bit too agressive to me.

Could you take a look at it?

Cheers,
Christoph

**Comment by ghost** [comment]
I'm not an expert on kernel programming but I'm reading the code and I'm interested in the default scheduler (because I plan to code an additional scheduler heavily based on this one). So I will take a look at it the following days and If I find a solution I will propose you a patch.

Cheers,
Christian

**Comment by cpaasch** [comment]
Good. I close this pull-request and let you update your patch.

Cheers,
Christoph

**Pull request closed without merging**
