### PR TITLE
Code improvements for the inclusion of the Redundant/ReMP scheduler

### PR DESCRIPTION
**Pull request by ghost**
Dear @cpaasch and @AlexanderFroemmgen,

I took the liberty of applying the changes proposed in #95 in order to include the redundant scheduler in the MPTCP Linux kernel.

I provide 1 commit with the intial @AlexanderFroemmgen's code and some additional commits with the required modifications that were pointed out in #95. I provide several commits in order to easily track the changes. Once accepted the patch, the final contribution could be compacted in one commit or two commits (one commit for @AlexanderFroemmgen's code and one for mine) or as you consider. 

Regarding the main changes:
- 585a7690add636b3c4fbc8fc4cb62d2c72633c42 improves the behaviour of reinjections and the use of backup subflows.
- 86422c8d818ec167e6c59b9f4cfe8dfa5fa786bb solves an error in KConfig to be able to select the redundant scheduler as the default MPTCP scheduler.
- 6a0d51ac9f2b6a0dc9ae8b5b1983975ee7f1d4f2 solves the coding errors pointed out by @cpaasch in #95
- 3d9ec72eabc00410ce481916491b43ce236aa2b3 Here I rename "ReMP" as "redundant" scheduler. I think that is the best name for the scheduler instead of ReMP, which is not so obvious. Do you agree @cpaasch and @AlexanderFroemmgen ?

Finally, this pull request should close #95

### CODE REVIEW

**Comment by cpaasch** [comment]
Hello Christian,

sorry for the late reply (incredibly busy at the moment).

Thanks for updating this pull-request.
Can you merge all these commits in a single one? Because, otherwise there would be issues when doing a `git bisect`.

Thanks,
Christoph

**Comment by ghost** [comment]
I initially prefer to manage small commits per objective pursued. Here, you have all in one single commit. Regards and don't worry about the time! :)

**Comment by forkjoseph** [comment]
sorry to comment this but I just ran some benches with and without redundancy scheduler. It looks like redundancy scheduler **hurts** overall performance even though small gain comes to us. It might be better to carefully look over the code before the merge.

**Comment by AlexanderFroemmgen** [comment]
1. @chrpinedo  
   Thanks a lot for continuing on this! 
2.  @forkjoseph 
   Can you elaborate/share your benchmarks? 
   In which scenarios does this happen?
   Does the performance with the default scheduler suffer?

**Comment by cpaasch** [comment]
Yes, please elaborate. Which measurements have been done and what were the results?

**Comment by cpaasch** [comment]
Merged this pull-request. I added EXPORT_SYMBOL_GPL, to allow compiling the scheduler as a module.

Thanks, @chrpinedo ! :)

**Comment by ghost** [comment]
I can't find the commit in the mptcp_trunk branch. Any problem?

**Comment by cpaasch** [comment]
Forgot to push :)

**Comment by ghost** [comment]
jajaj great! thanks! xD

**Pull request closed without merging**
