### PR TITLE
[v0.93] mptcp: Fix compilation error when CONFIG_MPTCP is undefined

### PR DESCRIPTION
**Pull request by lenormf**

### CODE REVIEW

**Comment by matttbe** [comment]
included in v0.93 via cherry-pick: https://github.com/multipath-tcp/mptcp/commit/0108f9ff0ec1904c02373e5e186f230c85d5d592

**Comment by lenormf** [comment]
This commit is different than the one in #331, hence the separate PR. It adds `mptcp_push_pending_frames()` to `mptcp.h`.

**Comment by matttbe** [comment]
@lenormf sorry, I only looked at the commit message and I didn't see the difference nor it had to be applied on top of #331 for v0.93 branch.
I will quickly fix that ;-)

**Comment by matttbe** [comment]
@lenormf I just saw this commit was not backported to v0.93: https://github.com/multipath-tcp/mptcp/commit/7454ef598678c7d70dacc493988581864855f3b1

Just did in v0.93: https://github.com/multipath-tcp/mptcp/commit/e5195c828bde657aa12506aee0dbf8add9c2bda2

**Comment by lenormf** [comment]
Great, cheers. Wasn't sure if I was supposed to create one commit that added the two functions on `mptcp_trunk`, or create two separate commits for the version branches (I did the latter, obviously).

**Comment by matttbe** [comment]
It was correct to have two commits. I will look at them more carefully next time. Don't hesitate to add as much useful info as possible in the commit message 🙂

**Pull request closed without merging**
